### ISSUE TITLE
Set up Github Actions to perform CI/CD ?

### ISSUE THREAD

**Issue by duongleh** [Marwan01/angular-cloudrun#2]
I love your content. Thank you so much.
However, I think you should find a way to automatically build and deploy your app after a new commit is pushed to the master branch.

**Comment by Marwan01** [comment]
Thanks! I agree! Adding CI/CD is the next logical step to get the process as hands-free as possible. I do have an article about CI/CD and continuous deployment to Github using Travis CI here is the link: https://medium.com/faun/ci-cd-with-travis-ci-and-firebase-20b6c69fa8f7

However, for this article, I limited the content just to deployment. I wrote a series of articles only about how to deploy web apps to different clouds. I wanted to keep them simple and limited to deploying only to avoid confusion especially for beginners deploying something for the first time.
